apiVersion: v1
kind: Namespace
metadata:
  name: bankdocs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bankdocs-backend
  namespace: bankdocs
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::361769597147:role/bankdocs-dev-backend-irsa