apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bankdocs
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: bankdocs-backend

      nodeSelector:
        workload: application

      containers:
        - name: backend
          image: 361769597147.dkr.ecr.us-east-1.amazonaws.com/bankdocs-dev-backend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-db-secret

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bankdocs
spec:
  type: ClusterIP

  selector:
    app: backend

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP